echo "Updating MiKTeX..."
mpm --require=ae
mpm --require=amscls
mpm --require=appendix
mpm --require=asymptote
mpm --require=atbegshi
mpm --require=atveryend
mpm --require=auxhook
mpm --require=babel-french
mpm --require=babel-german
echo "10%..."
mpm --require=babel-spanish
mpm --require=bbm
mpm --require=bibtex8bit
mpm --require=bibtex8bit-polish
mpm --require=bidi
mpm --require=bigintcalc
mpm --require=bitset
mpm --require=caption
mpm --require=carlisle
echo "20%..."
mpm --require=chktex
mpm --require=circuitikz
mpm --require=cleveref
mpm --require=ctex
mpm --require=cweb
mpm --require=cyrillic
mpm --require=dehyph-exptl
mpm --require=doublestroke
mpm --require=etex
echo "30%..."
mpm --require=etex-pkg
mpm --require=etexcmds
mpm --require=euenc
mpm --require=eurosym
mpm --require=float
mpm --require=fontname
mpm --require=geometry
mpm --require=gettitlestring
mpm --require=grfext
echo "40%..."
mpm --require=gsftopk
mpm --require=hycolor
mpm --require=infwarerr
mpm --require=intcalc
mpm --require=jknappen
mpm --require=knuth-local
mpm --require=koma-script
mpm --require=kvdefinekeys
mpm --require=kvoptions
echo "50%..."
mpm --require=kvsetkeys
mpm --require=latexindent
mpm --require=latexmk
mpm --require=letltxmacro
mpm --require=ltxcmds
mpm --require=ltxmisc
mpm --require=lua-alt-getopt
mpm --require=luainputenc
mpm --require=luamplib
echo "60%..."
mpm --require=luatexbase
mpm --require=luatextra
mpm --require=makeindex
mpm --require=mathtools
mpm --require=mflogo
mpm --require=mflogo-font
mpm --require=mfware
mpm --require=miktex-etex
mpm --require=miktex-metapost
echo "70%..."
mpm --require=miktex-omega
mpm --require=miktex-texinfo
mpm --require=multirow
mpm --require=pdfescape
mpm --require=pgfopts
mpm --require=polyglossia
mpm --require=poppler
mpm --require=preview
mpm --require=pslatex
echo "80%..."
mpm --require=psnfss
mpm --require=pstricks
mpm --require=psutils
mpm --require=refcount
mpm --require=rerunfilecheck
mpm --require=stringenc
mpm --require=texinfo
mpm --require=thumbpdf
mpm --require=ttf2pk
echo "90%..."
mpm --require=uniquecounter
mpm --require=urlbst
mpm --require=utopia
mpm --require=xecjk
mpm --require=xgreek
mpm --require=xindy
mpm --require=xltxtra
mpm --require=xunicode
mpm --require=xypic
mpm --require=zerohyph
mpm --require=zhnumber
echo "100%..."
